### ISSUE TITLE
Chapter 5 - Version 2 code locks up after Dialog is closed

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#1]
I set up a Python 3.7 virtual environment, installed sqlalchemy, ObjectListView, and wxPython via pip. The steps to recreate (at least on my system, MacOS 10.14.3, 32GB RAM, etc., 2018 iMac) are:

1. Open application
2. Add one record
3. Close dialog

I have to use Force Quit from the Apple menu to kill the Python instance.

**Comment by driscollis** [comment]
I think the problem is that I was calling `Destroy()` in a couple of the event handlers instead of `Close()`. This causes wxPython to try to call Destroy() a second time when it gets out of the `with` statement in `main.py`

Anyway, give the latest code a try and see if it is fixed. That seemed to fix it for my on my Mac

**Comment by cmcknight** [comment]
Hi Mike,

Yeah, that seems to have fixed it. :-)   And now on to Chapter 6 tomorrow. :-D

Regards,

Chuck

**Comment by cmcknight** [comment]
Hi Mike,

I’m assuming that the book text will be updated as well.  :-)

Chuck

P.S. Believe me that I do feel your pain. When I published an eBook on robotics there were 2-3 months where my end users were reporting defects that I had somehow missed and I was constantly editing things!  :-)

**Comment by driscollis** [comment]
Yes, I updated the book last night. You just need to download a new copy.

And I expect a lot of bugs for the next couple of months. That's part of why I do Kickstarters is to work out the kinks in the book. Thanks for the help!
